import { forwardRef } from 'react';
import { DashboardStats } from '../../../types/api';
import { ReportLayout } from './ReportLayout';
import { useSettings } from '../../../contexts/SettingsContext';

interface CommandCenterPDFProps {
    data: DashboardStats;
    periodText?: string;
    generatedBy?: string;
    serialNumber?: string;
}

export const CommandCenterPDF = forwardRef<HTMLDivElement, CommandCenterPDFProps>(
    ({ data, periodText, generatedBy, serialNumber }, ref) => {
        const { t } = useSettings();

        return (
            <ReportLayout
                ref={ref}
            >
                <div className="flex flex-col gap-8 mb-8">
                    {/* Document Serial Number Table */}
                    {serialNumber && (
                        <div className="mb-4 mt-2">
                            <table className="w-full text-sm text-left border-collapse border border-slate-300 shadow-sm">
                                <thead>
                                    <tr className="bg-slate-100 border-b border-slate-300">
                                        <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Document No.</th>
                                        <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Date of Issue</th>
                                        <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Period</th>
                                        <th className="p-3 font-bold uppercase tracking-wider text-slate-700 w-1/4">Generated By</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr className="bg-white">
                                        <td className="p-3 border-r border-slate-300 font-mono font-bold text-slate-900">{serialNumber}</td>
                                        <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>
                                        <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{periodText || 'All Time'}</td>
                                        <td className="p-3 font-medium text-slate-700">{generatedBy || 'System'}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    )}

                    <div className="text-center mb-2">
                        <h2 className="text-xl font-black text-slate-800 tracking-tight uppercase">{t('pdf.commandCenter.title')}</h2>
                        <p className="text-slate-600 font-medium text-sm">{t('pdf.commandCenter.subtitle')}</p>
                    </div>

                    {/* Recent Activity Table */}
                    <div>
                        <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-1 mb-2">
                            {t('pdf.detailedLogs')}
                        </h3>
                        <table className="w-full text-sm text-left align-top">
                            <thead>
                                <tr className="border-b border-slate-300 text-xs text-slate-500 font-bold uppercase tracking-wider">
                                    <th className="pb-3 pr-2 w-12 text-center">No.</th>
                                    <th className="pb-3 pr-2 w-1/3">{t('pdf.columns.title')}</th>
                                    <th className="pb-3 pr-2 w-1/6">{t('pdf.columns.author')}</th>
                                    <th className="pb-3 pr-2 w-1/6">{t('pdf.columns.editor')}</th>
                                    <th className="pb-3 pr-2 w-1/6">{t('pdf.columns.status')}</th>
                                    <th className="pb-3 text-right">{t('pdf.columns.date')}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {data.recentActivity.map((activity, index) => (
                                    <tr key={activity.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors">
                                        <td className="py-3 pr-2 text-slate-500 font-semibold text-xs text-center border-r border-slate-100/50">
                                            {index + 1}
                                        </td>
                                        <td className="py-3 px-2 text-slate-800 font-bold" title={activity.title}>
                                            {activity.title}
                                        </td>
                                        <td className="py-3 pr-2 text-slate-600 font-medium truncate" title={activity.authorName}>
                                            {activity.authorName || 'Unknown'}
                                        </td>
                                        <td className="py-3 pr-2 text-slate-600 font-medium truncate" title={activity.editorName}>
                                            {activity.editorName || 'None'}
                                        </td>
                                        <td className="py-3 pr-2">
                                            <span className="text-[10px] px-2 py-1 bg-slate-100 text-slate-600 font-bold uppercase rounded ring-1 ring-slate-200 break-keep">
                                                {activity.status}
                                            </span>
                                        </td>
                                        <td className="py-3 text-right text-xs font-mono text-slate-500 whitespace-nowrap">
                                            {new Date(activity.createdAt).toLocaleDateString()}
                                        </td>
                                    </tr>
                                ))}
                                {(!data.recentActivity || data.recentActivity.length === 0) && (
                                    <tr>
                                        <td colSpan={6} className="py-6 text-center text-slate-500 italic bg-slate-50 rounded-b-lg">
                                            {t('pdf.noReports')}
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </ReportLayout>
        );
    }
);

CommandCenterPDF.displayName = 'CommandCenterPDF';
