import { forwardRef } from 'react';
import { PersonnelStatsDTO } from '../../../types/api';
import { ReportLayout } from './ReportLayout';

interface PersonnelPDFProps {
    data: PersonnelStatsDTO;
    periodText?: string;
    generatedBy?: string;
    serialNumber?: string;
}

export const PersonnelPDF = forwardRef<HTMLDivElement, PersonnelPDFProps>(
    ({ data, periodText, generatedBy, serialNumber }, ref) => {
        return (
            <ReportLayout
                ref={ref}
            >
                {/* Document Serial Number Table */}
                {serialNumber && (
                    <div className="mb-4 mt-2">
                        <table className="w-full text-sm text-left border-collapse border border-slate-300 shadow-sm">
                            <thead>
                                <tr className="bg-slate-100 border-b border-slate-300">
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Document No.</th>
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Date of Issue</th>
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Period</th>
                                    <th className="p-3 font-bold uppercase tracking-wider text-slate-700 w-1/4">Generated By</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className="bg-white">
                                    <td className="p-3 border-r border-slate-300 font-mono font-bold text-slate-900">{serialNumber}</td>
                                    <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>
                                    <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{periodText || 'All Time'}</td>
                                    <td className="p-3 font-medium text-slate-700">{generatedBy || 'System'}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                )}

                <div className="text-center mb-2">
                    <h2 className="text-xl font-black text-slate-800 tracking-tight uppercase">Personnel Engagement</h2>
                    <p className="text-slate-600 font-medium text-sm">Activity Audit for Journalists and Editors</p>
                </div>

                {/* Journalists Section */}
                <div className="mb-8">
                    <h3 className="text-xl font-bold text-slate-800 border-b border-slate-300 pb-1 mb-2">
                        Journalist Performance
                    </h3>

                    <table className="w-full text-sm text-left text-slate-600">
                        <thead className="text-xs text-slate-700 uppercase bg-slate-50 border-b border-slate-300">
                            <tr>
                                <th scope="col" className="px-4 py-3 text-center w-12">No.</th>
                                <th scope="col" className="px-4 py-3">Name</th>
                                <th scope="col" className="px-4 py-3 text-center">Total Submitted</th>
                                <th scope="col" className="px-4 py-3 text-center">Verified</th>
                                <th scope="col" className="px-4 py-3 text-center">Rejected</th>
                                <th scope="col" className="px-4 py-3 text-right">Accuracy Rate</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.journalists.map((j, index) => (
                                <tr key={j.id} className="bg-white border-b border-slate-100 font-mono">
                                    <td className="px-4 py-3 text-slate-500 font-semibold text-center border-r border-slate-100/50">{index + 1}</td>
                                    <td className="px-4 py-3 font-medium text-slate-900 whitespace-nowrap overflow-hidden text-ellipsis max-w-[200px]" title={j.email}>
                                        <div>{j.name}</div>
                                        <div className="text-xs text-slate-400 font-sans">{j.email}</div>
                                    </td>
                                    <td className="px-4 py-3 text-center text-slate-500 font-bold">{j.totalReports}</td>
                                    <td className="px-4 py-3 text-center text-emerald-600 font-bold">{j.verifiedReports}</td>
                                    <td className="px-4 py-3 text-center text-rose-500">{j.rejectedReports}</td>
                                    <td className="px-4 py-3 text-right">
                                        <span className={`px-2 py-1 rounded font-bold ${j.accuracyRate > 80 ? 'bg-emerald-100 text-emerald-800' : j.accuracyRate > 50 ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-800'}`}>
                                            {j.accuracyRate.toFixed(1)}%
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {/* Editors Section */}
                <div>
                    <h3 className="text-xl font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4">
                        Editor Activity
                    </h3>

                    <table className="w-full text-sm text-left text-slate-600">
                        <thead className="text-xs text-slate-700 uppercase bg-slate-50 border-b border-slate-300">
                            <tr>
                                <th scope="col" className="px-4 py-3 text-center w-12">No.</th>
                                <th scope="col" className="px-4 py-3">Name</th>
                                <th scope="col" className="px-4 py-3 text-center">Total Reviews</th>
                                <th scope="col" className="px-4 py-3 text-center">Misinformation Flags Raised</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.editors.map((e, index) => (
                                <tr key={e.id} className="bg-white border-b border-slate-100 font-mono">
                                    <td className="px-4 py-3 text-slate-500 font-semibold text-center border-r border-slate-100/50">{index + 1}</td>
                                    <td className="px-4 py-3 font-medium text-slate-900 whitespace-nowrap overflow-hidden text-ellipsis max-w-[200px]" title={e.email}>
                                        <div>{e.name}</div>
                                        <div className="text-xs text-slate-400 font-sans">{e.email}</div>
                                    </td>
                                    <td className="px-4 py-3 text-center text-indigo-600 font-bold">{e.totalReviews}</td>
                                    <td className="px-4 py-3 text-center text-amber-600 font-bold">{e.flagsRaised}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </ReportLayout>
        );
    }
);

PersonnelPDF.displayName = 'PersonnelPDF';
