import { forwardRef } from 'react';
import { RiskAuditDTO } from '../../../types/api';
import { ReportLayout } from './ReportLayout';

interface RiskAuditPDFProps {
    data: RiskAuditDTO;
    periodText?: string;
    generatedBy?: string;
    serialNumber?: string;
}

export const RiskAuditPDF = forwardRef<HTMLDivElement, RiskAuditPDFProps>(
    ({ data, periodText, generatedBy, serialNumber }, ref) => {
        return (
            <ReportLayout
                ref={ref}
            >
                {/* Document Serial Number Table */}
                {serialNumber && (
                    <div className="mb-8 mt-2">
                        <table className="w-full text-sm text-left border-collapse border border-slate-300 shadow-sm">
                            <thead>
                                <tr className="bg-slate-100 border-b border-slate-300">
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Document No.</th>
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Date of Issue</th>
                                    <th className="p-3 border-r border-slate-300 font-bold uppercase tracking-wider text-slate-700 w-1/4">Period</th>
                                    <th className="p-3 font-bold uppercase tracking-wider text-slate-700 w-1/4">Generated By</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className="bg-white">
                                    <td className="p-3 border-r border-slate-300 font-mono font-bold text-slate-900">{serialNumber}</td>
                                    <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>
                                    <td className="p-3 border-r border-slate-300 font-medium text-slate-700">{periodText || 'All Time'}</td>
                                    <td className="p-3 font-medium text-slate-700">{generatedBy || 'System'}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                )}

                <div className="text-center mb-2">
                    <h2 className="text-xl font-black text-slate-800 tracking-tight uppercase">Misinformation & Risk Audit</h2>
                    <p className="text-slate-600 font-medium text-sm">Detailed Log of Flagged Reports</p>
                </div>

                <div>
                    <table className="w-full text-sm text-left align-top">
                        <thead>
                            <tr className="border-b border-slate-300 text-xs text-slate-500 font-bold uppercase tracking-wider">
                                <th className="pb-3 pr-2 w-12 text-center">No.</th>
                                <th className="pb-3 pr-2 w-1/3">Report Title</th>
                                <th className="pb-3 pr-2 w-1/6">Author</th>
                                <th className="pb-3 pr-2 w-1/6">Flagged By</th>
                                <th className="pb-3 pr-2">Reason</th>
                                <th className="pb-3 text-right whitespace-nowrap">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data.flaggedReports.map((report, idx) => (
                                <tr key={idx} className="border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors">
                                    <td className="py-3 pr-2 text-slate-500 font-semibold text-xs text-center border-r border-slate-100/50">
                                        {idx + 1}
                                    </td>
                                    <td className="py-3 px-2 text-slate-800 font-bold">
                                        #{report.reportId}: {report.reportTitle}
                                    </td>
                                    <td className="py-3 pr-2 text-slate-600 font-medium">
                                        {report.authorName}
                                    </td>
                                    <td className="py-3 pr-2">
                                        <span className="text-[10px] px-2 py-1 bg-rose-50 text-rose-700 font-bold uppercase rounded ring-1 ring-rose-200">
                                            {report.flaggedBy}
                                        </span>
                                    </td>
                                    <td className="py-3 pr-2 text-slate-600 text-xs whitespace-pre-wrap">
                                        {report.reason}
                                    </td>
                                    <td className="py-3 text-right text-xs font-mono text-slate-500 whitespace-nowrap">
                                        {new Date(report.flaggedAt).toLocaleDateString()}
                                    </td>
                                </tr>
                            ))}
                            {data.flaggedReports.length === 0 && (
                                <tr>
                                    <td colSpan={6} className="py-6 text-center text-slate-500 italic bg-slate-50 rounded-b-lg">
                                        No misinformation flags recorded in the current period.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </ReportLayout>
        );
    }
);

RiskAuditPDF.displayName = 'RiskAuditPDF';
